### ISSUE TITLE
[Feature Request] Add support for compiling shader code (text) to bytecode at runtime

### ISSUE THREAD

**Issue by geoeo** [mellinoe/veldrid#25] opened 2018-01-30 18:48 UTC
Hey,

I not sure how serious you are about supporting MacOS/Metal, but it would be a real QoL improvement if you could define the compilation of .metal files in the C# source.

Right now I'm doing this with a bash script and its fine for small projects.
But it would be so cool so have this done at source code level :) 

Best,
Marc

**Comment by mellinoe** [comment] 2018-01-30 19:53
This isn't Metal-specific -- right now with Veldrid all shader compilation should be done "offline", outside of the application. Except for OpenGL, which doesn't have precompiled shaders.

An version of Veldrid did have support for this, but I've left it out for now because I'm not sure what the answer is to some of these design questions:

* How are compiler arguments passed? There are probably common arguments that could be translated across compilers (define constants, optimization levels, etc.), but there's also some language-specific arguments that would be weird to expose.
* What happens when the "compilation tools" aren't available? It's my understanding that Metal and D3D11 always bundle the compiler into the OS, but Vulkan doesn't have that same guarantee. I'm also not really sure if mobile iOS devices, or things like XBox, have shader compilation capabilities at all.
* Should there be a single interface for shader compilation (e.g. `ResourceFactory.CompileShaderCode(string)`), or should there be per-language compilers (e.g. `MetalShaderCode.Compile(string)`, `HlslShaderCode.Compile(string)`, etc.).


Anyways, it is something I'd like to add, I'm just not sure about the best way to do it yet.

**Comment by geoeo** [comment] 2018-01-30 20:06
Hmm. You are right. Once the shaders are compiled its a done job. 

I just thought it would be cool to have a vanilla solution that just takes the names and produces compiled shaders through c# interop magic. But I guess that task is just better suited for build scripts.

**Comment by mellinoe** [comment] 2018-01-30 21:56
I've renamed the topic (hope you don't mind), because this is something I've thought about for a while and would like to track for the future.

**Comment by geoeo** [comment] 2018-01-31 16:34
Since this is tracked now. Maybe I can give a use case, which initiated this request.

# Use case
It should be possible to implement the [Getting Started Example ](https://mellinoe.github.io/veldrid-docs/articles/getting-started/intro.html) without using any binary files (shader or project) and external build scripts.

**Comment by Krakean** [comment] 2018-02-20 10:03
@mellinoe 
>How are compiler arguments passed? There are probably common arguments that could be translated across compilers (define constants, optimization levels, etc.), but there's also some language-specific arguments that would be weird to expose.

Would it make easy just to integrate ShaderGen to Veldrid? 
What most important thing in runtime shader compilation from my point of view - ability to write shaders directly in in-house world editor, and see result in real-time (just how it done in Godot - https://youtu.be/q0kZLH6sjxk?t=263, for example -- it has its own high-level shader language that wraps GLSL).

>What happens when the "compilation tools" aren't available? It's my understanding that Metal and D3D11 always bundle the compiler into the OS, but Vulkan doesn't have that same guarantee. I'm also not really sure if mobile iOS devices, or things like XBox, have shader compilation capabilities at all.

Just tell via code ("IsRuntimeShaderCompilationIsAvailable()" ?) that tool is not available. Thats it.

>Should there be a single interface for shader compilation (e.g. ResourceFactory.CompileShaderCode(string)), or should there be per-language compilers (e.g. MetalShaderCode.Compile(string), HlslShaderCode.Compile(string), etc.).

Single interface. Unlikely you gonna have situation when within same game application you have one frame rendered using D3D, and next one - via OGL :)

**Comment by mellinoe** [comment] 2018-02-20 19:26
> Would it make easy just to integrate ShaderGen to Veldrid?

ShaderGen isn't nearly mature or stable enough to include in Veldrid. It's still experimental and has a lot of bugs, and is very slow. Eventually this is a good idea, but I don't have enough time to dedicate to that project to make it good enough for inclusion directly with Veldrid. Realistically, it's probably a comparable workload to Veldrid itself.

> What most important thing in runtime shader compilation from my point of view - ability to write shaders directly in in-house world editor, and see result in real-time (for example - how it done in Godot - https://youtu.be/q0kZLH6sjxk?t=263 -- it has its own high-level shader language that wraps GLSL).

I'm planning to add this to own game engine -- if there's something re-usable from it I will try to share. It doesn't need anything integrated into Veldrid itself.

> Just tell via code ("IsRuntimeShaderCompilationIsAvailable()" ?) that tool is not available. Thats it.

Sure -- there may be multiple methods here, though, given the next question.

> Single interface. Unlikely you gonna have situation when within same game application you have one frame rendered using D3D, and next one - via OGL :)

The problem is these compilers have different options. We can include a single interface, but then we have to decide what the common settings are and how to abstract them.

> Unlikely you gonna have situation when within same game application you have one frame rendered using D3D, and next one - via OGL :)

If the game was built like NeoDemo is, then it is trivial to allow runtime switching of backends.

**Comment by Krakean** [comment] 2018-02-21 18:19
>ShaderGen isn't nearly mature or stable enough to include in Veldrid.

Then, may be its a good time to dedicate some attention to ShaderGen after swapchain branch merge? :)

>ShaderGen isn't nearly mature or stable enough to include in Veldrid.

You mean your's GE or your another private game engine?
And yes, would be nice if you share it with Veldrid.
I see workflow some kinda like this, in short:
1. Wrote shader on ShaderGen. Ctrl+S.
2. It compiled shader to current active (or one you explicitly specified) gfx api (lets say D3D11) and we get .hlsl source, and then we send it to Veldrid and it apply changed shader runtime and we see changes in real-time :)

>The problem is these compilers have different options. We can include a single interface, but then we have to decide what the common settings are and how to abstract them.

Not really getting this one. Why not do something like ->CompileShader(shader_text), and CompileShader() automatically call proper shader compile function (hlsl, glsl...) of current active gfxapi (i.e. it is hidden on veldrid side)?

>If the game was built like NeoDemo is, then it is trivial to allow runtime switching of backends.

So? Anyway at a time we can have only one particular active gfx backend.

**Comment by mellinoe** [comment] 2018-02-21 20:17
> Not really getting this one. Why not do something like ->CompileShader(shader_text), and CompileShader() automatically call proper shader compile function (hlsl, glsl...) of current active gfxapi (i.e. it is hidden on veldrid side)?

Sometimes it's not as easy to just hide. 

* The Metal language has multiple versions, which you need to specify when you compile the code. HLSL has the same thing ("profiles"), but those can probably be assumed to correspond to either D3D11 or D3D12 (assuming it's ever supported).
* Some languages require that you specify the stage that you are compiling:
  * HLSL `-T <profile>`
  * GLSL `-S <stage>`
  * Others don't care / need the info later
* HLSL requires that you pass an entry point (`-E <entry>`). Other languages need this later when you create a shader module or pipeline.
* A big one: there are multiple ways to produce SPIR-V bytecode. `glslangvalidator` is the "official" one, but you can also use [this project](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst). I would not be surprised if that actually becomes very popular since it allows you to use HLSL source.

> So? Anyway at a time we can have only one particular active gfx backend.

I was just responding to the notion that you wouldn't have one graphics API one frame and then another the next frame.

**Comment by mellinoe** [comment] 2018-02-23 02:07
Another problem I have discovered: Metal shaders need to be compiled differently on macOS and iOS, despite using the same API. There may be a way to make some kind of universal thing, but I'm not aware of it. It seems like they need to be separate.

**Comment by Krakean** [comment] 2018-02-23 11:06
>There may be a way to make some kind of universal thing, but I'm not aware of it. It seems like they need to be separate.

Then may be better to start with HLSL first, then Vulkan? And somewhere in between I suppose solution to Metal also would come :)
But after all, if Metal solution will be separated - can't much bad in it :)

**Comment by mellinoe** [comment] 2018-02-23 17:34
> Then may be better to start with HLSL first, then Vulkan? And somewhere in between I suppose solution to Metal also would come :)

The challenge is not in writing the code --  that part is easy. The challenge is in creating a consistent and useful abstraction that integrates well with the rest of Veldrid. As of right now I don't have one, so there's no point in starting to write code without an end goal.

> But after all, if Metal solution will be separated - can't much bad in it :)

The findings about Metal shaders indicate that it's not possible to provide a generic interface which only knows about the `GraphicsBackend` being used. The shader compiler will need to know the specific `GraphicsDevice` that it is targeting (sort of -- it's different from that but it's a close enough approximation).

**Comment by thargy** [comment] 2018-02-25 00:14
My two cents.

Rather than using statics, create a ShaderCode abstract class that defines a Compile(string) method, and a Backend readonly property.

Create descendants for each, e.g. MetalShaderCode, HlslShaderCode, which take options in their constructors and produce immutable objects.  Fix the Backend property in each.  If so inclined add a static CompileCode(string, options...) method by convention which is called by the the descendent Compile(string) instance method implementation passing the code and options - allowing users to call compilation directly passing options, to avoid object creation if so inclined.

Add static read only properties to each with useful instances (e.g. by convention always have a Default property).

Create a descendant called CombinedShaderCode which accepts multiple ShaderCode objects in its constructor, one for each supported BackEnd.  It’s compile implementation will call the Compile on the object that implements the current backend.  Again have a Default static readonly property which uses the Default implementations of  all the supported compilers.  Have the readonly Backend property just return the current Backend.

Also add a Compile overload that accepts a dictionary of Backend->Code, this will choose the code to compile from the dictionary and then call the relevant compiler. Or create new ShaderCodeCollection that collects code strings by backend.

This can then most easily be used immediately by calling CombinedShaderCode.Default.Compile(
{ { Backend.Metal, metalCodeStr }, ... });

But retains the ability to easily access more powerful and specific features when needed.

Writing on mobile so hope it makes sense!

**Comment by mellinoe** [comment] 2018-02-25 00:35
@thargy Conceptually it makes sense, but I think it's far more complicated than necessary. At this point, though, I'd really just like to understand what the public interface will look like. That's the only open question for me. Like I said, the implementation of this stuff is easy and obvious. These things are literally just going to shell out to external shader compilers and pass some arguments to them.

If every shading language is going to be surfaced in the public API, I'd rather it be done more simply. For example, there could just be three static classes, or three concrete, non-polymorphic classes. I think anything else is over-complicating it.

**Comment by thargy** [comment] 2018-02-25 00:45
@mellinoe fair enough, though I’m not sure I’d cal it complicated, it’s a pattern I use fairly regularly - it takes longer to describe than code really; and it’s very discoverable and easy to use by consumers.

My primary goal was to maintain your own design goal of Code Once for consumers, so the library should be created to avoid the need to test the GraphicsBackend in a Switch statement wherever possible.  Such a pattern allows code once whilst leaving specific implementations accessible.

Anyway it’s a nice project, glad I stumbled across it.

**Comment by mellinoe** [comment] 2018-02-25 01:55
> My primary goal was to maintain your own design goal of Code Once for consumers, so the library should be created to avoid the need to test the GraphicsBackend in a Switch statement wherever possible. 

That's definitely what I'm aiming for as well. We could certainly try to prototype both versions and see which one "feels" better, if we end up wanting to expose all of the languages individually.

I'll throw out a really basic strawman of what I think it could look like, with my current understanding of what's needed. This is taking a "unified" approach, with no language-specific stuff exposed.

```C#
namespace Veldrid
{
    public static class ShaderCompilation
    {
        public static byte[] CompileShader(string shaderText, ShaderCompilationOptions options, GraphicsDevice device);
        public static bool IsCompilationSupported(GraphicsDevice device, ShadingLanguage language);
    }

    public struct ShaderCompilationOptions
    {
        public ShadingLanguage Language;
        public string EntryPoint;
        public string[] DefineConstants; // A bunch of strings like "KEY=VALUE", "KEY", etc.
        public bool Optimize; // False == no optimizations, full debuggability, True == full optimization
    }

    public enum ShadingLanguage
    {
        Default, // The "normal" language for the GraphicsDevice being used.
        HLSL,
        Metal,
        GLSL,
    }
}
```

**Comment by feliwir** [comment] 2018-05-25 19:34
In theory veldrid could determine by itself if it processing a binary shader or a text shader. This could be done by analysising the first few bytes. A binary shader usually starts with some kind of magic:

- HLSL Bytecode: `0x44 0x58 0x42 0x43`
- Metal Bytecode: unknown
- SpirV Bytecode: `0x07230203`

With this approach no additional complexity would be exposed to the user of the library.

**Comment by mellinoe** [comment] 2018-05-25 22:33
I made a [shader-compile branch](https://github.com/mellinoe/veldrid/tree/shader-compile) that supports compiling HLSL and Metal shaders at runtime.

If `ShaderDescription.ShaderBytes` contains text rather than bytecode, then the D3D11 and Metal backends will compile the code and use it. There is also a `ShaderDescription.Debug` option that can be used to suppress optimizations for the compilation.

**Comment by mellinoe** [comment] 2018-06-06 04:36
Closing the loop on this one.

The branch above has been merged into master, so you are now able to compile HLSL and Metal shaders at runtime. [The documentation](https://mellinoe.github.io/veldrid-docs/articles/shaders.html#creating-a-shader) needs to be updated, but the new features are pretty straightforward:

* D3D11: ShaderBytes must contain HLSL bytecode **or HLSL text (Shader Model 5)**
* Metal: ShaderBytes must contain Metal bytecode **or Metal text**

The final remaining question is: How do I compile Vulkan shaders at runtime? Unfortunately, there's no great way to do it without taking on additional native dependencies. @feliwir has a project [here](https://github.com/feliwir/SharpShaderCompiler) that lets you interface with the native `glslang` compiler library. For the time being, I don't plan on adding direct support for GLSL->SPIR-V compilation into Veldrid, but there should be no problems with using that library to compile your code.

**Closed by mellinoe** 2018-06-06 04:36 UTC
