### ISSUE TITLE
CommandList.Name in VS Graphics Debugger

### ISSUE THREAD

**Issue by pzgulyas** [mellinoe/veldrid#152] opened 2019-01-19 11:54 UTC
The CommandList.Name is not getting through into the Visual Studio Graphics Analyzer (Direct3D/Windows). Even if I set it, I just see e.g.:

T001 2719: obj:2 -> ExecuteCommandList(obj:840,0)

Other names that I set, appear between brackets, like e.g.:

T001 2728: obj:2 -> UpdateSubresource(Somename,0,nullptr,addr,112,112)

**Comment by mellinoe** [comment] 2019-01-19 18:07
Thanks for reporting this, I can confirm it's an issue. The fix seems to be pretty straightforward from my testing. While Veldrid is currently setting the DebugName of the deferred ID3D11DeviceContext for each CommandList, it doesn't set the DebugName of the ID3D11CommandList that is created when commands are finished recording. The latter name is what actually gets displayed in the debugger, so it's currently unset. I will push the fix shortly.

**Comment by mellinoe** [comment] 2019-01-19 18:15
@pzgulyas This should be fixed with this commit: https://github.com/mellinoe/veldrid/commit/cb3cb9bcc35b55d2d81145a107e64b80e1378384

Thanks again for letting me know about the issue.

**Comment by mellinoe** [comment] 2019-01-20 06:05
This should be fixed now, and will be included in the next release. Let me know if you encounter any more issues.

**Closed by mellinoe** 2019-01-20 06:05 UTC
