### ISSUE TITLE
Crash in VkCommandList.CommandBufferSubmitted

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#135] opened 2018-11-22 09:58 UTC
![stacktrace](https://user-images.githubusercontent.com/6377116/48895117-63469100-ee55-11e8-9f82-fc3d177da131.png)

This happened only once in the last few months, so I don't really have a repro.

**Comment by mellinoe** [comment] 2018-11-26 07:56
I believe I have a fix for this on a local branch, which I'm currently working on getting merged up for 4.5.0. I'll follow up here once the commit is linkable.

**Comment by mellinoe** [comment] 2018-12-03 09:51
I believe the problem is fixed by this commit: https://github.com/mellinoe/veldrid/commit/2c0c4e8a61af2ac55a1e3dd9a99862031ba7dc31.

There was a timing issue related to the order in which items were being added that could have resulted in this exception.

I'll close this out for now; please re-open if there is a recurrence.

**Closed by mellinoe** 2018-12-03 09:51 UTC
