### ISSUE TITLE
The type initializer for 'Vulkan.VulkanNative' searchs for 'liblibdl' instead of 'libdl'

### ISSUE THREAD

**Issue by adryzz** [mellinoe/veldrid#461] opened 2022-10-09 10:08 UTC
`Veldrid.GraphicsDevice.CreateVulkan(options, swapChainDescription);` throws a `DllNotFoundException`, saying it cannot find `libdl` while it is searching for `liblibdl`, and thus doesn't find anything.

```
System.TypeInitializationException: The type initializer for 'Vulkan.VulkanNative' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libdl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibdl: cannot open shared object file: No such file or directory
   at Vulkan.Libdl.dlerror()
   at Vulkan.NativeLibrary.UnixNativeLibrary.LoadLibrary(String libraryName)
   at Vulkan.NativeLibrary..ctor(String libraryName)
   at Vulkan.NativeLibrary.UnixNativeLibrary..ctor(String libraryName)
   at Vulkan.NativeLibrary.Load(String libraryName)
   at Vulkan.VulkanNative.LoadNativeLibrary()
   at Vulkan.VulkanNative..cctor()
   --- End of inner exception stack trace ---
   at Vulkan.VulkanNative.vkEnumerateInstanceLayerProperties(UInt32& pPropertyCount, VkLayerProperties* pProperties)
   at Veldrid.Vk.VulkanUtil.EnumerateInstanceLayers()
   at Veldrid.Vk.VkGraphicsDevice.CreateInstance(Boolean debug, VulkanDeviceOptions options)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc, VulkanDeviceOptions vkOptions)
   at Veldrid.Vk.VkGraphicsDevice..ctor(GraphicsDeviceOptions options, Nullable`1 scDesc)
   at Veldrid.GraphicsDevice.CreateVulkan(GraphicsDeviceOptions options, SwapchainDescription swapchainDescription)
   at Sekai.Veldrid.VeldridGraphicsDevice.initializeVulkan(GraphicsDeviceOptions options, SwapchainDescription swapChainDescription)
```

**Comment by TheAirBlow** [comment] 2022-10-22 09:29
This error is misleading. Basically, it first tries `libdl.so`, then `liblibdl.so`. The problem is that you need to symlink `libdl.so.2` or whatever the file is to `libdl.so` for it to work.

**Comment by lawrence-laz** [comment] 2022-12-22 17:30
Maybe it should also look for `libdl.so.2` the same way it searches for `liblibdl.so`?

**Comment by TheAirBlow** [comment] 2022-12-22 19:52
> Maybe it should also look for `libdl.so.2` the same way it searches for `liblibdl.so`?

Usually package managers create a symlink automatically

**Comment by lawrence-laz** [comment] 2022-12-22 20:32
> > Maybe it should also look for `libdl.so.2` the same way it searches for `liblibdl.so`?
> 
> Usually package managers create a symlink automatically

I am on a pretty popular distro:
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
```
and it didn't.

It's not a big deal, but if we have a precedence of checking `liblibdl.so` it seems like the same logic could be applied to checking for `libdl.so.2`. Seems like quite a few people keep stepping on this rake.

**Comment by mellinoe** [comment] 2022-12-22 21:37
This should be fixed on the master branch now with the updated version of `NativeLibraryLoader`.

**Closed** 2022-12-28 03:23 UTC
