### ISSUE TITLE
Add support for DirectX 12

### ISSUE THREAD

**Issue by snaulX** [mellinoe/veldrid#392] opened 2021-06-10 11:31 UTC
You can add support for DirectX 12 using Vortice.DirectX12

**Comment by feliwir** [comment] 2021-06-15 08:53
Duplicate of https://github.com/mellinoe/veldrid/issues/68
We already know this and even with Vortice there still goes a lot of effort into this. I and @amerkoleci  aswell already tried this before

**Comment by mellinoe** [comment] 2021-06-15 09:07
Yep, dupe of #68

**Closed by mellinoe** 2021-06-15 09:07 UTC
