### ISSUE TITLE
Vulkan RenderSets

### ISSUE THREAD

**Issue by skyne98** [mellinoe/veldrid#71] opened 2018-05-09 13:05 UTC
Hey there! 
I have been writing some stuff lately and have struck what seems to me like a bug. While using an OpenGL backend code works perfectly and renders a couple of transformed images with a help of a simple shader. However, when I switch to a Vulkan renderer, it seems like it doesn't create the resource sets, described by the ResourceLayout-s.

Here is an Exception:
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Veldrid.Vk.VkCommandList.SetGraphicsResourceSetCore(UInt32 slot, ResourceSet rs)
   at Neptune.Engine.Sample.SimpleRenderer.Draw() in /media/skyne/ExternalDrive/projects/Neptune/Engine/Sample/SimpleRenderer.cs:line 47
   at Neptune.Engine.Sample.SimpleRenderer.BatchDraw(Action`1 action) in /media/skyne/ExternalDrive/projects/Neptune/Engine/Sample/SimpleRenderer.cs:line 38
   at Neptune.Engine.Sample.SimpleGame.Render(RenderInfo info) in /media/skyne/ExternalDrive/projects/Neptune/Engine/Sample/SimpleGame.cs:line 49
   at Neptune.Program.Main() in /media/skyne/ExternalDrive/projects/Neptune/Program.cs:line 39

Thanks for your attention!

**Comment by mellinoe** [comment] 2018-05-09 15:51
Could you provide some more information about how you are using your `CommandList` before this exception occurs? What calls have you made before calling `SetGraphicsResourceSet` ?

**Comment by skyne98** [comment] 2018-05-09 16:36
Sure, those are the calls:
```_commandList.Begin();
            _commandList.SetFramebuffer(_graphicsDevice.SwapchainFramebuffer);
            _commandList.SetFullViewports();
            _commandList.ClearColorTarget(0, RgbaFloat.Black);
            _commandList.SetGraphicsResourceSet(0, _resourceSet);
            for (var i = 0; i < _vertexBuffers.Count; i++)
            {
                _commandList.SetVertexBuffer(0, _vertexBuffers[i]);
                _commandList.SetIndexBuffer(_indexBuffers[i], IndexFormat.UInt16);
                _commandList.SetPipeline(_pipeline);                       
                _commandList.DrawIndexed(
                    indexCount: 4,
                    instanceCount: 1,
                    indexStart: 0,
                    vertexOffset: 0,
                    instanceStart: 0);   
            }
            _commandList.End();
            _graphicsDevice.SubmitCommands(_commandList);
            _graphicsDevice.SwapBuffers();
```
And that's how I get it:
```
_commandList = _resourceFactory.CreateCommandList();
```

**Comment by skyne98** [comment] 2018-05-09 16:37
That's the whole CreateResources() method
```
        private void CreateResources()
        {
            _resourceFactory = _graphicsDevice.ResourceFactory;

            VertexLayoutDescription vertexLayout = new VertexLayoutDescription(
                new VertexElementDescription("vin_position", VertexElementSemantic.Position, VertexElementFormat.Float2),
                new VertexElementDescription("vin_texcoord", VertexElementSemantic.TextureCoordinate, VertexElementFormat.Float2),
                new VertexElementDescription("vin_color", VertexElementSemantic.Color, VertexElementFormat.Float4));

            _vertexShader = LoadShader(ShaderStages.Vertex);
            _fragmentShader = LoadShader(ShaderStages.Fragment);

            GraphicsPipelineDescription pipelineDescription = new GraphicsPipelineDescription();
            pipelineDescription.BlendState = BlendStateDescription.SingleOverrideBlend;
            
            pipelineDescription.DepthStencilState = new DepthStencilStateDescription(
                depthTestEnabled: true,
                depthWriteEnabled: true,
                comparisonKind: ComparisonKind.LessEqual);

            pipelineDescription.RasterizerState = new RasterizerStateDescription(
                cullMode: FaceCullMode.Back,
                fillMode: PolygonFillMode.Solid,
                frontFace: FrontFace.Clockwise,
                depthClipEnabled: true,
                scissorTestEnabled: false);

            pipelineDescription.PrimitiveTopology = PrimitiveTopology.TriangleStrip;

            var resourceLayout = _resourceFactory.CreateResourceLayout(new ResourceLayoutDescription(
                new ResourceLayoutElementDescription("sprite_texture", ResourceKind.TextureReadOnly, ShaderStages.Fragment)
            ));
            
            pipelineDescription.ResourceLayouts = new[]
            {
                resourceLayout
            };

            pipelineDescription.ShaderSet = new ShaderSetDescription(
                vertexLayouts: new VertexLayoutDescription[] { vertexLayout },
                shaders: new Shader[] { _vertexShader, _fragmentShader });

            pipelineDescription.Outputs = _graphicsDevice.SwapchainFramebuffer.OutputDescription;
            _pipeline = _resourceFactory.CreateGraphicsPipeline(pipelineDescription);

            _commandList = _resourceFactory.CreateCommandList();
            
            // Create the resource set
            var texture = new ImageTexture("Assets/doge.jpg").CreateDeviceTexture(_graphicsDevice, _resourceFactory);
            var view = _resourceFactory.CreateTextureView(texture);
            
            _resourceSet = _resourceFactory.CreateResourceSet(new ResourceSetDescription(
                resourceLayout,
                view
            ));   
        }
```

**Comment by mellinoe** [comment] 2018-05-09 16:50
I believe the problem is that you are binding the Pipeline after you bind the ResourceSet. Binding a new Pipeline will "invalidate" the ResourceSets you had bound previously. In your case you should be able to just move the `_commandList.SetPipeline(_pipeline);` call up above the `_commandList.SetGraphicsResourceSet(0, _resourceSet);` call. This should probably be documented more clearly, and the OpenGL backend should probably be less permissive in this regard.

Can you try the above and make sure it works?

**Comment by skyne98** [comment] 2018-05-09 17:47
Seems to have worked, thanks! However, I don't think it's very intuitive and lots of people might end up with the same issue. Maybe mention it in the docs?

Also, I have one less related question. For some reason, my code and shaders work only on OpenGL. Compiling shaders with glslang and using the resulting libraries always result in a black window. Am I doing something wrong and there are other backend-specific stuff I have to wrap my head around?

**Comment by mellinoe** [comment] 2018-05-09 17:57
> However, I don't think it's very intuitive and lots of people might end up with the same issue. Maybe mention it in the docs?

Yes, I definitely agree. I'm going to add some extra validation here and update the docs.

> Also, I have one less related question. For some reason, my code and shaders work only on OpenGL. Compiling shaders with glslang and using the resulting binaries always result in a black window. Am I doing something wrong and there are other backend-specific stuff I have to wrap my head around?

There are a few differences between backends that you need to account for, mainly with regards to clip space coordinates (the output of your vertex shader):

https://mellinoe.github.io/veldrid-docs/articles/backend-differences.html

**Comment by skyne98** [comment] 2018-05-09 18:02
Yeah, I had a suspicion it has something to do with coordinates, as I wasn't able to get anything even from the fragment shader. Also, haven't seen that article for some reason, is that new?

**Comment by mellinoe** [comment] 2018-05-09 18:04
It's fairly old, actually. I added it after a similar question in the past 😄

**Comment by skyne98** [comment] 2018-05-09 18:10
Anyways, it's quite unfortunate that there is no easy way to use GLSL only without any code transformation. (However, if it comes down to adding those two lines in the end, it might be easy to add those automagically).

By the way, isn't glslang itself capable of doing the required trickery? It has some options to set different targets.

**Comment by mellinoe** [comment] 2018-05-09 18:50
glslangvalidator does have a `--invert-y` flag, but that only covers part of the clip-space differences. OpenGL-flavor GLSL is quite a bit different from Vulkan-flavor GLSL, though, so I'm not sure it's feasible to actually fully share code between them. You need to specify all of the binding points in Vulkan-flavor GLSL, and there are some other semantic differences from what I understand.

**Comment by skyne98** [comment] 2018-05-09 18:52
The main reason is to make writing shaders more understandable, approachable and easy. As far as I know, Unity tackles that problem by using CG, which can then be used on any platform.

**Comment by skyne98** [comment] 2018-05-09 18:58
Also, what about SPIRV-Cross project? It seems like it was done with that problem in mind.

**Comment by mellinoe** [comment] 2018-05-09 19:08
Right, the main solution used in other projects is to translate one shading language into all others. Unity must do something like that with their shaders. SPIRV-Cross can be used to generate a bunch of different kinds of shaders from SPIR-V bytecode. [ShaderGen](https://github.com/mellinoe/shadergen) is my attempt to support writing shaders in C# and auto-generate code for all of the supported backends in Veldrid. It works well enough at the moment but still has a lot of rough edges.

> About bindings: as far as I can tell, it's not really a problem, you can enforce writing them for all platforms.

I'm not sure if OpenGL drivers allow those bindings to be used. `glslangvalidator` complains about them unless the "Vulkan semantics" flag is used (`-V`).

**Comment by skyne98** [comment] 2018-05-09 19:17
> I'm not sure if OpenGL drivers allow those bindings to be used. glslangvalidator complains about them unless the "Vulkan semantics" flag is used (-V).

I am using the same shader for both OpenGL and cross-compilation. It works on Windows and Linux on both backends just fine.

>  ShaderGen is my attempt to support writing shaders in C# and auto-generate code for all of the supported backends in Veldrid. It works well enough at the moment but still has a lot of rough edges.

Yeah, incredible work! However, I want to hear your thoughts on trying to use currently official and well-maintained tools. As both glsland and SPRIV-Cross have good C++ bindings, it might be pretty straightforward to transpile C# into GLSL, or SPIRV IR and then leverage SPIRV-Cross to do all the other work.

**Comment by skyne98** [comment] 2018-05-09 19:33
```
Usage: spirv-cross
	[--output <output path>]
	[SPIR-V file]
	[--es]
	[--no-es]
	[--version <GLSL version>]
	[--dump-resources]
	[--help]
	[--force-temporary]
	[--vulkan-semantics]
	[--flatten-ubo]
	[--fixup-clipspace]
	[--flip-vert-y]
	[--iterations iter]
	[--cpp]
	[--cpp-interface-name <name>]
	[--msl]
	[--msl-version <MMmmpp>]
	[--hlsl]
	[--shader-model]
	[--hlsl-enable-compat]
	[--separate-shader-objects]
	[--pls-in format input-name]
	[--pls-out format output-name]
	[--remap source_name target_name components]
	[--extension ext]
	[--entry name]
	[--stage <stage (vert, frag, geom, tesc, tese comp)>]
	[--remove-unused-variables]
	[--flatten-multidimensional-arrays]
	[--no-420pack-extension]
	[--remap-variable-type <variable_name> <new_variable_type>]
	[--rename-interface-variable <in|out> <location> <new_variable_name>]
	[--set-hlsl-vertex-input-semantic <location> <semantic>]
	[--rename-entry-point <old> <new> <stage>]
```

These are the spriv-cross options. Take a look at ones such as "--fixup-clipspace", or "--flip-vert-y".

**Comment by mellinoe** [comment] 2018-05-09 20:03
SPIRV-Cross is certainly a good option -- I'm sure you could use it to generate shaders for Veldrid to use, but probably not "out of the box". The last time I looked at it, I wasn't able to understand how to get it to remap between Vulkan-like descriptor indices and a flat layout for D3D11-style HLSL. I think it required writing some amount of C++ to control the configuration it uses to cross-compile stuff, but I didn't go that far.

The obvious downside to SPIRV-Cross is that it's C++ -- it will make your .NET app more difficult to build on different platforms, and it will add another programming language and build toolchain into the mix. That's certainly not a deal breaker, but I find that stuff pretty painful in the long run.

**Comment by skyne98** [comment] 2018-05-09 20:10
Yeah, I see, but I still think that the cost of adding another language is much smaller, than the cost of writing your own transpiler for all the platforms and keeping it up to date. I might be wrong, though, as those don't update too often.

**Comment by mellinoe** [comment] 2018-05-09 23:32
Going back to the original issue, I added some extra validation that will catch additional error conditions. An exception will now be thrown if you:

* Try to bind a ResourceSet without setting a Pipeline first
* Try to bind a ResourceSet to a slot that is invalid (e.g. it's too high for the active Pipeline
* Try to bind a ResourceSet that doesn't have the correct number or types of resources

I'm happy to continue chatting about shader generation (you're always welcome in [the chat room](gitter.im/veldrid/Lobby)), but I'll close this one out as I think the problem is solved.

**Closed by mellinoe** 2018-05-09 23:32 UTC
