### ISSUE TITLE
Render target binding as texture view D3D11

### ISSUE THREAD

**Issue by drjaydenm** [mellinoe/veldrid#247] opened 2020-01-14 11:31 UTC
Hi @mellinoe, this is the bug that I was talking about on Gitter the other day where using a render target as a texture view binding doesn't always work on D3D11 backend.

Tl;dr of the bug as far as I can see is:
* First render pass writes to render target 1 and has render target 2 as a texture view binding
* A second render pass runs writing to render target 2 with a different shader which has no texture bindings (this implicitly unbinds render target 2 from the first shader)
* A third render pass runs writing back to render target 1 with render target 2 as a texture view binding again - this time, the texture view binding doesn't get bound back to the shader properly

I've done a little digging and it looks like when render target 2 gets unbound, it isn't removed from the list of bound texture views in D3D11CommandList, therefore in the third pass, it thinks it is already bound and doesn't actually bind it properly (I could be way off here though).
Let me know if you have any questions

PR for the repro test is here: #248

**Comment by mellinoe** [comment] 2020-01-16 04:38
Thank you for the detailed description and for the repro code. The problem is very likely a bug in the tracking of bound resources, esp. regarding render target and shader resource views. I will take a closer look at this soon.

**Comment by mellinoe** [comment] 2020-01-23 07:44
This should be fixed now: https://github.com/mellinoe/veldrid/commit/9b16d7e9390b8cf466c4b21232313418f0e8b2c7

**Closed by mellinoe** 2020-01-23 07:44 UTC

**Comment by drjaydenm** [comment] 2020-01-23 09:00
Thanks for taking a look and getting a fix up so quickly 😄
