### ISSUE TITLE
Merge branch "sdl2-mouse-additions"

### ISSUE THREAD

**Issue by erictuvesson** [mellinoe/veldrid#72] opened 2018-05-09 16:20 UTC
Hey, could you merge the "sdl2-mouse-additions" branch? 
I would really like to have the mouse functionality.

**Comment by mellinoe** [comment] 2018-05-09 16:52
Sure, I think it's pretty useful as well. It would be nice if there was also a way to get the "Mouse Delta" rather than just the absolute position, and perhaps that delta could ignore changes caused by SetMousePosition. With just SetMousePosition, you'll have to keep track of that separately.

**Comment by mellinoe** [comment] 2018-05-09 16:57
I merged https://github.com/mellinoe/veldrid/commit/6394869af0477d259922541325357f8b5303e82b, so SetMousePosition is now available.

**Closed by mellinoe** 2018-05-09 16:58 UTC
