### ISSUE TITLE
A call to PInvoke function 'SDL_CreateWindow_t::Invoke' has unbalanced the stack

### ISSUE THREAD

**Issue by Herbstein** [mellinoe/veldrid#17] opened 2017-12-21 02:33 UTC
This is using the full source code from the tutorial part 1. I'm using the newest Nuget release and targeting .net framework 4.7.

**Comment by mellinoe** [comment] 2017-12-21 03:12
Hm, this is almost certainly because of some bad PInvoke signatures. I'll have to look into it.

Are you testing x86, by chance? It would be good to know if this still happens on a 64-bit target.

**Comment by Herbstein** [comment] 2017-12-21 03:29
I've taken a screenshot of the full Exception. ([Imgur](https://imgur.com/a/NpGK6))

I was using the default Any Cpu target, which prefers x86. Switched it to x64 and it's working as intended.

**Comment by mellinoe** [comment] 2017-12-21 03:35
Yeah, I believe the problem is the SDL2 imports are missing the `CallingConvention.Cdecl` property. I will test out that fix soon.

**Comment by Herbstein** [comment] 2017-12-21 03:38
Would be a good idea to mention. A project in VS prefers x86 by default. A lot of people would get caught by that.

**Comment by mellinoe** [comment] 2017-12-21 04:56
This is fixed in https://github.com/mellinoe/veldrid/commit/444d3295bf97346ffafdbdd0960c96fdce91d0a8.

I will be releasing a beta2 sometime in the next week or so with a few fixes like this rolled up into it. In the meantime you can continue using a 64-bit app, or you could use the packages from MyGet if you'd like.

**Closed by mellinoe** 2017-12-21 04:56 UTC
