### ISSUE TITLE
[OpenGL] Textures are always bound to unit 0

### ISSUE THREAD

**Issue by SomeAnon42** [mellinoe/veldrid#57] opened 2018-03-17 20:11 UTC
...in places other than ``ActivateResourceSet``. So, basically, if a texture is bound as a result of calling any other method (such as ``Map`` or ``CopyTexture``), it always ends up in unit 0.
And that can become a problem.
Imagine this scenario: you have a sampler in your shader bound to texture unit 0. In the meantime, a background thread is trying to load a new image. In the end, ``CopyTexture`` is called, which causes it to be bound to unit 0. As a result, the newly created texture is sampled instead of the original one.
For instance, in a 2D game, that would mean that whenever a new texture is loaded on a background thread, it is briefly displayed on the screen, as it replaces the texture that was previously in unit 0.

**Comment by mellinoe** [comment] 2018-03-17 22:57
I understand the problem and I've verified a basic fix. I think this warrants doing a bit of cleanup related to how texture binding is handled more broadly, because it's too messy right now and there are probably other subtle issues with how the binding state is tracked. For example, because OpenGL objects are lazily initialized, there could be some other obscure issues where initializing the textures at an unexpected time could override the cached state.

Practically, I think everything needs to go through the OpenGLTextureSamplerManager if it ever touches the texture units. On top of that, the command executor probably needs to flush the resource sets right before a draw call and not assume that the texture units have been undisturbed. That will be more expensive than what I'm currently doing, but it should be fine.

As a mitigation, I these "one-off texture usages" should bind to the upper-most texture units that are available, because those are extremely unlikely to be in use. Doing so would avoid any real conflicts 99% of the time.

**Comment by mellinoe** [comment] 2018-03-18 03:24
@SomeAnon42 I have a fix here: https://github.com/mellinoe/veldrid/commit/4e25323875ec2b96070aad596c4d89601c8d9883.

I'm going to run a few more tests on it on different platforms before merging it into master, but I think it is mostly correct.

**Comment by mellinoe** [comment] 2018-03-18 20:18
@SomeAnon42 Are you able to tes tout whether your scenario is fixed by the change? I did add a regression test that should match what you were seeing: https://github.com/mellinoe/veldrid/blob/4e25323875ec2b96070aad596c4d89601c8d9883/src/Veldrid.Tests/RenderTests.cs#L425

**Comment by SomeAnon42** [comment] 2018-03-18 22:00
Yes, everything is fine now.

**Comment by mellinoe** [comment] 2018-03-18 22:05
@SomeAnon42 Awesome, thanks for the report and the testing.

**Closed by mellinoe** 2018-03-18 22:05 UTC
