### ISSUE TITLE
NeoDemo crashes using vulkan

### ISSUE THREAD

**Issue by emmauss** [mellinoe/veldrid#104] opened 2018-07-24 12:30 UTC
The demo works normally in all other backend, but when using vulkan, it crashes when you turn to look at the upper part green curtains just on your right at start point. It occurs at https://github.com/mellinoe/veldrid/blob/f6196c302013b8674faae71e77e11bdd88559c20/src/NeoDemo/Objects/TexturedMesh.cs#L316 , and it throws an AccessViolationException
I am testing in on a Geforce 840m, on Windows 10 1803 update

**Comment by mellinoe** [comment] 2018-07-24 15:15
Hey @emmauss , I'm sorry you had trouble with the Vulkan backend. Would you be willing to install the Vulkan SDK and then run NeoDemo in Debug mode? It could give more valuable information as to what went wrong.

https://vulkan.lunarg.com/sdk/home#windows

Does the program run correctly until you turn and face a certain object?

**Comment by emmauss** [comment] 2018-07-24 16:45
yeah . It runs normally till i turn. and always at that place. I can turn to that place on other backends, switch to vulkan and then it will crash. I can start looking forward, change to vulkan before turning, then crash.

**Comment by emmauss** [comment] 2018-07-24 17:53
Done the above. this time is breaks in DebugCallback in VkGraphicDevice . the full message is 
```
[ErrorEXT] (FenceEXT)  [ VUID-vkResetFences-pFences-01123 ] Object: 0x19 (Type = 7) | Fence 0x19 is in use. The spec valid usage text states 'Each element of pFences must not be currently associated with any queue command that has not yet completed execution on that queue' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkResetFences-pFences-01123)```

**Comment by emmauss** [comment] 2018-07-24 17:56
the next entry in the call stack is this `>	Veldrid.dll!Veldrid.Vk.VkGraphicsDevice.SwapBuffersCore(Veldrid.Swapchain swapchain) Line 340	C#
`

**Comment by mellinoe** [comment] 2018-07-24 18:55
What version of the Nvidia drivers are you using? When I updated to the latest, I experienced a ton of bizarre errors (in NeoDemo and in other programs like Chrome) that went away when I reverted to an earlier version.

**Comment by emmauss** [comment] 2018-07-24 19:54
I use driver version 398.36.

**Comment by mellinoe** [comment] 2018-07-24 21:32
Hm, that is the version that I experienced a lot of problems with. I will try to re-install it sometime soon and see if I get any further. From what I recall, I wasn't even able to run other Vulkan demo programs (e.g. [Sascha Willem's](https://github.com/SaschaWillems/Vulkan)), so it didn't seem Veldrid-specific.

**Comment by mellinoe** [comment] 2018-07-25 03:15
Well, I was going to say that other Vulkan examples were working and Veldrid wasn't, but now I have hit a new persistent error that wasn't happening before. Now, vkCreateSwapchainKHR is failing with an access violation every time, which means I can't even get into the real rendering code. This is happening in other Vulkan code as well, not just Veldrid. Some of Sascha's examples still work, but as far as I can tell, all of his code uses the same swapchain creation logic. Only some of them crash on vkCreateSwapchainKHR, as Veldrid does. I'm not sure how to diagnose this -- still leaning towards driver issues. I've also looked over the swapchain synchronization code and I believe it is correct (although I can't get that far anymore...)

**Comment by mellinoe** [comment] 2018-07-25 20:42
It turns out the crash I was seeing in vkCreateSwapchainKHR was [caused by the Steam overlay](https://www.reddit.com/r/vulkan/comments/91r967/update_your_drivers_if_vkcreateswapchainkhr/). I'm still not sure what is causing the problem, as I believe the synchronization around swapchains is correct already.

**Comment by mellinoe** [comment] 2018-09-26 14:39
I fixed several issues in the Vulkan backend related to Swapchain resizing and queue submission tracking, but there's still a bad issue occurring on my GTX 770 when using the Vulkan backend. I've determined that changing the depth format away from R32_Float fixes it for me, but I have no idea why that would be the case. I am in the process of updating to VK_EXT_debug_utils to see if I get any more actionable validation information than what I currently have.

**Comment by mellinoe** [comment] 2018-10-27 06:56
Since I've done quite a bit of hardening in the Vulkan backend recently, I'm going to close this out unless I hear there are some remaining issues.

**Closed by mellinoe** 2018-10-27 06:56 UTC

**Comment by AlzPatz** [comment] 2020-01-01 13:51
Hi, sorry to resurrect the thread, but seemed like the right place.

On WINDOWS I find that switching backends to VULKAN fails if OPENGL has been used previously. It fails with an access violation error, which under debug is described as: 

Veldrid.VeldridException. HResult = 0x80131500. Message = A Vulkan validation error was encountered: [ErrorEXT](SwapchainKHREXT) vkCreateSwapchainKHR: internal drawable creation failed.

This does NOT occur using LINUX (UBUNTU and ARCH distros tested). I have not tried iOS.

I believe this type of error is very broad and could be due to a number of factors. 

I post this here as i'd love to hear if anyone else experiences the same issue. I have created a small example which cycles through available backends. You can also create an exclusion list (I used this for testing to narrow down the issue to one between OpenGL and Veldrid).

I've read a comment somewhere suggesting issues can occur when an OpenGL context is used erroneously with VULKAN. I've no idea if that is a thread to explore. I also haven't delved into driver versions / testing yet. Hoping it's something more simple on the Veldrid side first. I am unsure at this stage how or if I have the time to deep dive into the cause. Apologies for being lazy and posting here without doing much debugging myself

https://github.com/AlzPatz/VeldridApiSwitchingIssue

Appreciate in advance hearing if this replicates for anyone or any observations anyone has

As a final bit of background, I came across this in a more complex project that actually does do some rendering operations beyond just clearing the default swap chain, so I do not think it is an issue with the absence of any real rendering pipeline or operations, etc

**Comment by mellinoe** [comment] 2020-01-01 19:24
@AlzPatz Usually, that error occurs when you try to create a Vulkan device for a window that has already been used for OpenGL previously. Unfortunately, I don’t think there’s a quick fix for that, since it is a driver-level limitation. The workaround that NeoDemo uses is to recreate the entire window when switching backends. You can remember the size/position/state of the window and restore it so that the transition is fairly seamless.

If you aren’t seeing that problem (eg you aren’t trying to reuse the same window) then please open a new issue since I haven’t seen that problem before.

**Comment by AlzPatz** [comment] 2020-01-02 08:12
Thanks Eric. Yes I have been using the same window, will rejig things to create new on a transition to Vulkan. Although I haven’t tested it yet, a window issue with some OpenGL context overhang also fits with where I thought the issue was coming from.

Thanks again :)

**Comment by AlzPatz** [comment] 2020-01-02 21:23
Creating a new window works :) It seems that pulling Window.Y from the current Window and feeding into WindowInfo.Y (as neo demo does) results in shifting the window down by the height of the title bar. Same happens with Window.Bounds.Top. I can see why this would happen (the y you feed window creation will be the top including title bar and y stored in window would then be top of window client area. To adjust for this I'd imagine you would have to measure OS window title height cross platform, which is probablya little tricky, so don't think its something that needs modifying given how infrequently i expect to change backends. 

thanks again for the help.
